# Generated by Django 3.0.5 on 2020-04-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0003_auto_20200402_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='owner',
        ),
    ]
