# Generated by Django 3.0.5 on 2020-04-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0004_remove_person_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
