# Generated by Django 3.0.5 on 2020-04-02 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0007_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(max_length=9)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_book.Person')),
            ],
        ),
    ]
