# Generated by Django 3.0.5 on 2020-04-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0008_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
