# Generated by Django 3.0.5 on 2020-04-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0009_auto_20200402_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
