# Generated by Django 3.0.5 on 2020-04-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0010_auto_20200402_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=9, unique=True),
        ),
    ]
