# Generated by Django 3.0.5 on 2020-04-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0014_auto_20200403_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
