# Generated by Django 3.0.5 on 2020-04-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0015_auto_20200404_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
